### ISSUE TITLE
Unknown tag @ISO

### ISSUE THREAD

**Issue by ghost** [sagmor/yard-mruby#11]
When I run `mrbdoc` to generate the yard docs I get an error saying **[warn]: Unknown tag @ISO in file `mrblib/enum.rb` near line 14**. Everything still gets generated just fine anyways but I was just wondering why it's there if the tag is supposedly unknown?

**Comment by sagmor** [comment]
My bad,
I added the TAG but forgot to release a new version of the gem.

I'll push a new release tomorrow that should fix the issue.

**Comment by ghost** [comment]
Thank you!

**Comment by sagmor** [comment]
@Mav7 v0.2.1 is out with support for the @ISO tag :wink:

**Comment by ghost** [comment]
@sagmor Great thanks man! Works like a charm :) One more thing though I getting a warning saying `[warn]: Error loading plugin 'yard-coderay'` This probably something I messed up on. Any idea what might be going on there?

**Comment by sagmor** [comment]
Sure,

To support C syntax highlighting on MRuby's examples ([like here](https://github.com/mruby/mruby/blob/814328595608a6eb6a2d1b7578d3151d47f9be79/include/mruby.h#L197-L205)) I used also [yard-coderay](https://github.com/sagmor/yard-coderay) because by default YARD only has a highlighter for Ruby.

a simple `gem install yard-coderay` should be enough.

**Comment by ghost** [comment]
@sagmor Thanks again man! Also great work on this gem!

**Comment by sagmor** [comment]
No prob! glad it's useful
